name: Publish a release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git credentials
        run: ./.github/bin/set-credentials

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.2.6'
      
      - name: Install Nim build tools
        run: ./.github/bin/install-build-tools
      
      # - name: Bump version and push tag
      #   run: ./bin/release

      - name: Build binary
        run: ./bin/build

      - name: Set current tag
        run: ./.github/bin/export-version

      - name: Test
        run: printenv

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tooling_webserver
          asset_name: tooling_webserver
          tag: $VERSION
          overwrite: true
